### PR TITLE
Redux api

### PR DESCRIPTION
**Pull request by Lul-Abdifan**
### In this milestone, I have done the following:-

 -  Make use of the Bookstore API
 -  Use Axios to make HTTP requests to the backend
 -  Fetch  books from the Bookstore API after the component has rendered
 -  Refactor add book and remove book features to persist the changes in the server
    -  Add Crud functionality of the API
 -   Test the project if it behaves the same way after refactoring is done
    

I appreciate your understanding and patience. If you have any questions or concerns, please don't hesitate to reach out to me at @Lul-Abdifan. :desktop_computer:coding:desktop_computer:

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
### Hi @Lul-Abdifan, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Correct Git-flow followed :100: 
- [ ] PR and commit messages looks professional :rocket: awesome
- [ ] No linter errors recorded :+1: 
- [ ] `createAsyncThunk` is imported in the project :fireworks: 
- [ ] Action creator `getBooks` exists in the bookSlice file :1st_place_medal: 
- [ ] HTTP requests are done with `axios` :100: 
- [ ] `useEffect` is used when dispatching the `getBooks` function in `<Books>` compoenent :rocket: 
- [ ] Add and remove book functionality works as expected :fireworks: 

## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be better if we remove the live demo link, since it is not project specific, it makes our README looks unprofessional. Kindly remove it to improve our README file :man_technologist: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lul-Abdifan** [comment]
@addod19  Thank you for your feedback. I will take it into consideration.  happy coding. :desktop_computer:

**Comment by addod19** [comment]
> @addod19 Thank you for your feedback. I will take it into consideration. However, I would like to clarify that your previous suggestion was merely an optional suggestion, as I understand that it may not be the right time for deployment and my project is not complete yet. happy coding. desktop_computer

@Lul-Abdifan, no please, this is not an optional comment, for all non-working/broken links or misleading links that prevent our README file from being professional. So it would be better to put a 'Under construction` text instead of misleading links

**Comment by Lul-Abdifan** [comment]
@addod19  I understand Thank you.

**Review by KayLemba — APPROVED** [review]
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @Lul-Abdifan       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] linters are passing
- [x] Professional README 💯
- [x] Api setup correctly and running as intended 💯 
 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



well-1

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

[OPTIONAL] It would be nice to add your coding partners contact infomation to the Authors section because this is a pair programming exercise.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

**Comment by Lul-Abdifan** [comment]
@KayLemba
I appreciate your review and approval.
 I see a solo project on my dashboard, could you please describe clearly the  Optional Suggestion?
Happy Coding :smile:

**Pull request merged**
